module.exports = [
    {
        id: '1',
        imgUrl: require('../images/courtsupervision/tingshijianguan.png'),
        name: '庭室监管',
        child: [
            {
                id: '1-1',
                imgUrl: require('../images/courtsupervision/lawguanli.png'),
                imgUrl2: require('../images/courtsupervision/lawguanli2.png'),
                name: '法庭管理',
                url: '/indexmain/courtmanagement',
            },
            // {
            //     id:'1-2',
            //     imgUrl: require('../images/courtsupervision/xietiaoguanli.png'),
            //     imgUrl2: require('../images/courtsupervision/xietiaoguanli2.png'),
            //     name: '调解室管理',
            //     url: '/indexmain/mediationroom',
            // },
            // {
            //     id:'1-3',
            //     imgUrl: require('../images/courtsupervision/zhengrenshi.png'),
            //     imgUrl2: require('../images/courtsupervision/zhengrenshi.png'),
            //     name: '证人室管理',
            //     url: '/indexmain/witnessroom',
            // },
            // {
            //     id:'1-4',
            //     imgUrl: require('../images/courtsupervision/yuanchengtingshi.png'),
            //     imgUrl2: require('../images/courtsupervision/yuanchengtingshi2.png'),
            //     name: '远程庭审室管理',
            //     url: '/indexmain/remoteroom',
            // },
        ]
    },
    {
        id: '2',
        imgUrl: require('../images/courtsupervision/serverguanli.png'),
        name: '服务器监管',
        url: '/indexmain/Serversupervision',
    },
    {
        id: '3',
        imgUrl: require('../images/courtsupervision/musicvideogl.png'),
        name: '庭审音视频管理',
        url: '/indexmain/musicvideoment',
    },
    // {
    //     id:'4',
    //     imgUrl: require('../images/courtsupervision/cunchuqianyi.png'),
    //     name: '存储迁移管理',
    //     url: '/indexmain/storagemigration',
    // },
    {
        id: '5',
        imgUrl: require('../images/courtsupervision/caseguanli.png'),
        name: '案件管理',
        child: [
            {
                id: '5-1',
                imgUrl: require('../images/anjinaguanli/anjianxinxi.png'),
                imgUrl2: require('../images/anjinaguanli/anjianxinxi2.png'),
                name: '案件信息管理',
                url: '/indexmain/CaseInformation',
            },
            {
                id: '5-2',
                imgUrl: require('../images/anjinaguanli/paiqiguanli.png'),
                imgUrl2: require('../images/anjinaguanli/paiqiguanli2.png'),
                name: '排期管理',
                url: '/indexmain/CaseManagement',
            },
            {
                id: '5-3',
                imgUrl: require('../images/anjinaguanli/delete.png'),
                imgUrl2: require('../images/anjinaguanli/delete2.png'),
                name: '回收站',
                url: '/indexmain/RecycleBin',
            },
            {
                id: '5-4',
                imgUrl: require('../images/anjinaguanli/guoqi.png'),
                imgUrl2: require('../images/anjinaguanli/guoqi2.png'),
                name: '过期排期管理',
                url: '/indexmain/OverdueScheduling',
            },
        ]
    },
    {
        id: '6',
        imgUrl: require('../images/courtsupervision/yingyongpeizhi.png'),
        name: '应用配置',
        child: [
            {
                id: '6-1',
                imgUrl: require('../images/yingyongpeizhi/tingshipeizhi.png'),
                imgUrl2: require('../images/yingyongpeizhi/tingshipeizhi2.png'),
                name: '庭室配置',
                url: '/indexmain/courtyardallocation',
            },
            {
                id: '6-2',
                imgUrl: require('../images/yingyongpeizhi/remote.png'),
                imgUrl2: require('../images/yingyongpeizhi/remote2.png'),
                name: '远程庭审相关配置',
                url: '/indexmain/remoteconfig',
            },
            {
                id: '6-3',
                imgUrl: require('../images/yingyongpeizhi/liumeitipeizhi.png'),
                imgUrl2: require('../images/yingyongpeizhi/liumeitipeizhi2.png'),
                name: '流媒体服务器配置',
                url: '/indexmain/media',
            },
            {
                id: '6-4',
                imgUrl: require('../images/yingyongpeizhi/pingtaipeizhi.png'),
                imgUrl2: require('../images/yingyongpeizhi/pingtaipeizhi2.png'),
                name: '平台配置',
                url: '/indexmain/platform',
            },
            {
                id: '6-5',
                imgUrl: require('../images/yingyongpeizhi/internet.png'),
                imgUrl2: require('../images/yingyongpeizhi/internet2.png'),
                name: '互联网开庭相关配置',
                url: '/indexmain/interNetConfig',
            },
            {
                id: '6-6',
                imgUrl: require('../images/yingyongpeizhi/fatingwaiwei.png'),
                imgUrl2: require('../images/yingyongpeizhi/fatingwaiwei2.png'),
                name: '法庭外围系统配置',
                url: '/indexmain/outerring',
            },
            {
                id: '6-7',
                imgUrl: require('../images/yingyongpeizhi/fatingfuzhu.png'),
                imgUrl2: require('../images/yingyongpeizhi/fatingfuzhu2.png'),
                name: '法庭辅助服务器配置',
                url: '/indexmain/assist',
            },
            {
                id: '6-8',
                imgUrl: require('../images/yingyongpeizhi/banbenshengji.png'),
                imgUrl2: require('../images/yingyongpeizhi/banbenshengji2.png'),
                name: '版本升级管理',
                url: '/indexmain/versionUpgrade',
            },
            {
                id: '6-9',
                imgUrl: require('../images/yingyongpeizhi/jichushujvpeizhi.png'),
                imgUrl2: require('../images/yingyongpeizhi/jichushujvpeizhi2.png'),
                name: '基础数据配置',
                url: '/indexmain/basicdata',
            },
            {
                id: '6-10',
                imgUrl: require('../images/yingyongpeizhi/shenliyewu.png'),
                imgUrl2: require('../images/yingyongpeizhi/shenliyewu2.png'),
                name: '审理业务配置',
                url: '/indexmain/trialbusiness',
            },
            {
                id: '6-11',
                imgUrl: require('../images/yingyongpeizhi/xitongpeizhi.png'),
                imgUrl2: require('../images/yingyongpeizhi/xitongpeizhi2.png'),
                name: '系统配置',
                url: '/indexmain/systemConfig',
            },
            {
                id: '6-12',
                imgUrl: require('../images/yingyongpeizhi/qitapeizhi.png'),
                imgUrl2: require('../images/yingyongpeizhi/qitapeizhi2.png'),
                name: '其它配置',
                url: '/indexmain/otherconfig',
            }
        ]
    },
    // {
    //     id:'7',
    //     imgUrl: require('../images/courtsupervision/tongjifenxi.png'),
    //     name: '统计分析',
    //     url: '/indexmain/storagemigration',
    // },
    {
        id: '8',
        imgUrl: require('../images/courtsupervision/xitongguanli.png'),
        name: '系统管理',
        child: [
            {
                id: '8-1',
                imgUrl: require('../images/xitongguanli/bumenguanli.png'),
                imgUrl2: require('../images/xitongguanli/bumenguanli2.png'),
                name: '部门管理',
                url: '/indexmain/DepartmentManagement',
            },
            {
                id: '8-2',
                imgUrl: require('../images/xitongguanli/zhiwuguanli.png'),
                imgUrl2: require('../images/xitongguanli/zhiwuguanli2.png'),
                name: '职务管理',
                url: '/indexmain/PositionManagement',
            },
            {
                id: '8-3',
                imgUrl: require('../images/xitongguanli/juese-quanxian.png'),
                imgUrl2: require('../images/xitongguanli/juese-quanxian2.png'),
                name: '角色-权限管理',
                url: '/indexmain/Roleprivilege',
            },
            {
                id: '8-4',
                imgUrl: require('../images/xitongguanli/yonghuguanli.png'),
                imgUrl2: require('../images/xitongguanli/yonghuguanli2.png'),
                name: '用户管理',
                url: '/indexmain/UserManagement',
            },
            // {
            //     id: '8-5',
            //     imgUrl: require('../images/xitongguanli/rizhiguanli.png'),
            //     imgUrl2: require('../images/xitongguanli/rizhiguanli2.png'),
            //     name: '日志管理',
            //     url: '/indexmain/LogManagement',
            // },
        ]
    },
    {
        id:'9',
        imgUrl: require('../images/courtsupervision/lawpolicrecord.png'),
        name: '法警报警记录管理',
        url: '/indexmain/bailiffAlarm',
    },
    // {
    //     id:'10',
    //     imgUrl: require('../images/courtsupervision/tongzhiinfo.png'),
    //     name: '通知信息',
    //     url: '/indexmain/storagemigration',
    // },
    // {
    //     id: '11',
    //     imgUrl: require('../images/courtsupervision/testcaseguanli.png'),
    //     name: '测试信息管理',
    //     url: '/indexmain/Testcase',
    // },
]
